version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: postgresql
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: bts
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend

  liquibase-migrations:
    image: liquibase/liquibase:4.18
    container_name: liquibase
    restart: on-failure
    depends_on:
      - postgres
    command:
      - --hub-mode=off
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/bts
      - --username=user
      - --password=secret
      - update
    volumes:
      - ./migrations:/liquibase/changelog
    networks:
      - backend

  radio-component-service:
    container_name: app
    image: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SERVER_PORT= 8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/bts
      - APP_CORS_ALLOWED-ORIGINS=http://localhost:3000
    networks:
      - backend

volumes:
  postgres-data:

networks:
  backend:
    driver: bridge